@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class BillFormat <<Pivot>> {
    id : String
    href : String
    description : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}


'processing edges for BillFormat
@enduml